name: Update README2
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
